# -*- coding: utf-8 -*-
"""Ahmar_Hassan_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1my_IGmqIHD2EffGXEZuz7-MNgxe4YZuJ
"""

# ==========================================
# PART 1: DATA PROCESSING & SPLITTING
# ==========================================
import os
import glob
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from pathlib import Path
from google.colab import drive

# 1. Mount Google Drive
drive.mount('/content/drive')

# 2. Define Base Directory
base_dir = Path("/content/drive/MyDrive/final_images_C")

# 3. Aggregate Data
filepaths = list(base_dir.glob(r'**/*.jpeg')) + list(base_dir.glob(r'**/*.jpg')) + list(base_dir.glob(r'**/*.png'))

# 4. Extract Labels from Folder Names
labels = [os.path.split(os.path.split(x)[0])[1] for x in filepaths]

filepaths = pd.Series(filepaths, name='Filepath').astype(str)
labels = pd.Series(labels, name='Label')

# 5. Create DataFrame
df = pd.concat([filepaths, labels], axis=1)
print(f"Classes found: {df['Label'].unique()}")

# 6. Create the Split (70% Train, 15% Val, 15% Test)
train_df, dummy_df = train_test_split(df, train_size=0.7, shuffle=True, random_state=42, stratify=df['Label'])
val_df, test_df = train_test_split(dummy_df, train_size=0.5, shuffle=True, random_state=42, stratify=dummy_df['Label'])

print(f"\nTrain Images: {len(train_df)}")
print(f"Val Images:   {len(val_df)}")
print(f"Test Images:  {len(test_df)}")

# 7. Visualize Distribution
plt.figure(figsize=(6,4))
sns.countplot(x=train_df['Label'])
plt.title("Training Data Distribution")
plt.show()

"""# Step 2: Model 1 - Keras (Functional API)
Architecture: Standard Transfer Learning. DenseNet121 -> GlobalAveragePooling -> Dense(256) -> Dropout -> Output.
"""

# ==========================================
# MODEL 1: KERAS (Functional API)
# ==========================================
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import DenseNet121
from tensorflow.keras.applications.densenet import preprocess_input
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout, Input
from tensorflow.keras.models import Model

# 1. Image Generators
train_gen = ImageDataGenerator(
    preprocessing_function=preprocess_input,
    rotation_range=20,
    zoom_range=0.2,
    horizontal_flip=True
)
test_gen = ImageDataGenerator(preprocessing_function=preprocess_input)

# 2. Data Loaders
train_data_keras = train_gen.flow_from_dataframe(
    train_df, x_col='Filepath', y_col='Label',
    target_size=(224, 224), class_mode='binary', batch_size=32, shuffle=True
)
val_data_keras = test_gen.flow_from_dataframe(
    val_df, x_col='Filepath', y_col='Label',
    target_size=(224, 224), class_mode='binary', batch_size=32, shuffle=False
)
test_data_keras = test_gen.flow_from_dataframe(
    test_df, x_col='Filepath', y_col='Label',
    target_size=(224, 224), class_mode='binary', batch_size=32, shuffle=False
)

# 3. Define Model
def build_keras_model():
    input_img = Input(shape=(224, 224, 3))
    base_model = DenseNet121(weights='imagenet', include_top=False, input_tensor=input_img)
    base_model.trainable = False # Freeze base

    x = base_model.output
    x = GlobalAveragePooling2D()(x)
    x = Dense(256, activation='relu')(x)
    x = Dropout(0.5)(x)
    output = Dense(1, activation='sigmoid')(x)

    model = Model(inputs=input_img, outputs=output, name="Keras_Functional")
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    return model

keras_model = build_keras_model()

# 4. Train
print("\n--- Training Keras Model ---")
history_keras = keras_model.fit(
    train_data_keras,
    validation_data=val_data_keras,
    epochs=10
)

"""## EfficientNet using keras"""

# ==========================================
# MODEL: EFFICIENTNET (Custom Top)
# ==========================================
from keras.applications import EfficientNetB4
from keras.layers import Dense, GlobalAveragePooling2D, Dropout, BatchNormalization
from keras.models import Model

# 1. Define Model
def build_efficientnet_model():

    base_model = EfficientNetB4(
        weights='imagenet',
        include_top=False,
        input_shape=(224, 224, 3)
    )

    base_model.trainable = False  # Freeze base model

    x = base_model.output
    x = GlobalAveragePooling2D()(x)
    x = BatchNormalization()(x)   # Stability (same as your TF model)
    x = Dense(128, activation='relu')(x)
    x = Dropout(0.5)(x)
    output = Dense(1, activation='sigmoid')(x)

    model = Model(inputs=base_model.input, outputs=output, name="EfficientNet_Custom")

    model.compile(
        optimizer='adam',
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    return model


# 2. Build Model
efficientnet_model = build_efficientnet_model()

# 3. Train
print("\n--- Training EfficientNet Model ---")
history_efficientnet = efficientnet_model.fit(
    train_data_keras,
    validation_data=val_data_keras,
    epochs=30
)

"""# Model 2 - TensorFlow (Custom Top)
Architecture: Enhanced architecture for medical imaging. DenseNet121 -> GlobalAveragePooling -> BatchNormalization -> Dense(128) -> Dropout -> Output.
"""

# ==========================================
# MODEL 2: TENSORFLOW (Custom Top)
# ==========================================
from tensorflow.keras.layers import BatchNormalization

# 1. Define Model (Loaders are same as Keras above)
def build_tf_custom_model():
    base_model = DenseNet121(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
    base_model.trainable = False

    x = base_model.output
    x = GlobalAveragePooling2D()(x)
    x = BatchNormalization()(x) # <--- Added for stability
    x = Dense(128, activation='relu')(x)
    x = Dropout(0.5)(x)
    output = Dense(1, activation='sigmoid')(x)

    model = Model(inputs=base_model.input, outputs=output, name="TF_Custom")
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    return model

tf_model = build_tf_custom_model()

# 2. Train
print("\n--- Training TensorFlow Custom Model ---")
history_tf = tf_model.fit(
    train_data_keras, # Reuse generators
    validation_data=val_data_keras,
    epochs=10
)

"""## Efficentnet using tensorflow"""

# ==========================================
# MODEL: TENSORFLOW EFFICIENTNET (Custom Top)
# ==========================================
import tensorflow as tf
from tensorflow.keras.applications import EfficientNetB0   # safer choice
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout, BatchNormalization
from tensorflow.keras.models import Model

# 1. Define Model
def build_tf_efficientnet_model():

    base_model = EfficientNetB0(
        weights='imagenet',
        include_top=False,
        input_shape=(224, 224, 3)
    )

    base_model.trainable = False  # Freeze base model

    x = base_model.output
    x = GlobalAveragePooling2D()(x)
    x = BatchNormalization()(x)   # Stability
    x = Dense(128, activation='relu')(x)
    x = Dropout(0.5)(x)
    output = Dense(1, activation='sigmoid')(x)

    model = Model(inputs=base_model.input, outputs=output, name="TF_EfficientNet")

    model.compile(
        optimizer='adam',
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    return model


# 2. Build Model
tf_efficientnet_model = build_tf_efficientnet_model()

# 3. Train
print("\n--- Training TensorFlow EfficientNet Model ---")
history_tf_eff = tf_efficientnet_model.fit(
    train_data_keras,
    validation_data=val_data_keras,
    epochs=30
)

"""## Model 3 - PyTorch
Architecture: Standard PyTorch DenseNet with custom classifier. DenseNet121 -> Linear(1024, 256) -> ReLU -> Dropout -> Linear(256, 1).
"""

# ==========================================
# MODEL 3: PYTORCH
# ==========================================
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import models, transforms
from torch.utils.data import Dataset, DataLoader
from PIL import Image

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# 1. Custom Dataset
class ChestXRayDataset(Dataset):
    def __init__(self, dataframe, transform=None):
        self.dataframe = dataframe
        self.transform = transform
        # Dynamic Label Mapping
        self.class_map = {label: idx for idx, label in enumerate(dataframe['Label'].unique())}
        print(f"PyTorch Class Map: {self.class_map}")

    def __len__(self):
        return len(self.dataframe)

    def __getitem__(self, idx):
        img_path = self.dataframe.iloc[idx]['Filepath']
        label_str = self.dataframe.iloc[idx]['Label']
        label = self.class_map[label_str]
        image = Image.open(img_path).convert('RGB')
        if self.transform:
            image = self.transform(image)
        return image, torch.tensor(label, dtype=torch.float32)

# 2. Transforms
pt_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

# 3. Loaders
train_ds = ChestXRayDataset(train_df, transform=pt_transform)
val_ds = ChestXRayDataset(val_df, transform=pt_transform)
test_ds = ChestXRayDataset(test_df, transform=pt_transform)

train_loader = DataLoader(train_ds, batch_size=32, shuffle=True)
val_loader = DataLoader(val_ds, batch_size=32, shuffle=False)
test_loader = DataLoader(test_ds, batch_size=32, shuffle=False)

# 4. Model Definition
pt_model = models.densenet121(weights='IMAGENET1K_V1')
for param in pt_model.parameters():
    param.requires_grad = False # Freeze

num_ftrs = pt_model.classifier.in_features
pt_model.classifier = nn.Sequential(
    nn.Linear(num_ftrs, 256),
    nn.ReLU(),
    nn.Dropout(0.5),
    nn.Linear(256, 1),
    nn.Sigmoid()
)
pt_model = pt_model.to(device)

# 5. Training Loop (Simplified)
criterion = nn.BCELoss()
optimizer = optim.Adam(pt_model.classifier.parameters(), lr=0.001)

pt_acc_history = []
pt_loss_history = []

print("\n--- Training PyTorch Model ---")
for epoch in range(10):
    pt_model.train()
    running_loss = 0.0
    correct = 0
    total = 0
    for inputs, labels in train_loader:
        inputs, labels = inputs.to(device), labels.unsqueeze(1).to(device)
        optimizer.zero_grad()
        outputs = pt_model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()
        predicted = (outputs > 0.5).float()
        correct += (predicted == labels).sum().item()
        total += labels.size(0)

    epoch_acc = correct / total
    pt_acc_history.append(epoch_acc)
    pt_loss_history.append(running_loss / len(train_loader))
    print(f"Epoch {epoch+1}: Loss {running_loss/len(train_loader):.4f} Acc {epoch_acc:.4f}")

"""## efficent net using pyrorch

"""

# ==========================================
# MODEL: PYTORCH EFFICIENTNET (Custom Top)
# ==========================================
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import models

# Device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# 1. Load Pretrained EfficientNet
pt_eff_model = models.efficientnet_b0(weights='IMAGENET1K_V1')  # Use b0 (safe)

# 2. Freeze base layers
for param in pt_eff_model.features.parameters():
    param.requires_grad = False

# 3. Modify classifier (same idea as TF custom top)
num_ftrs = pt_eff_model.classifier[1].in_features

pt_eff_model.classifier = nn.Sequential(
    nn.Linear(num_ftrs, 128),
    nn.ReLU(),
    nn.Dropout(0.5),
    nn.Linear(128, 1),
    nn.Sigmoid()
)

# Move to device
pt_eff_model = pt_eff_model.to(device)

# ==========================================
# TRAINING SETUP
# ==========================================
criterion = nn.BCELoss()
optimizer = optim.Adam(pt_eff_model.classifier.parameters(), lr=0.001)

# ==========================================
# TRAINING LOOP
# ==========================================
num_epochs = 30

print("\n--- Training PyTorch EfficientNet Model ---")

for epoch in range(num_epochs):
    pt_eff_model.train()
    running_loss = 0.0
    correct = 0
    total = 0

    for inputs, labels in train_loader:
        inputs = inputs.to(device)
        labels = labels.unsqueeze(1).to(device)

        optimizer.zero_grad()

        outputs = pt_eff_model(inputs)
        loss = criterion(outputs, labels)

        loss.backward()
        optimizer.step()

        running_loss += loss.item()

        predicted = (outputs > 0.5).float()
        correct += (predicted == labels).sum().item()
        total += labels.size(0)

    epoch_acc = correct / total
    epoch_loss = running_loss / len(train_loader)

    print(f"Epoch {epoch+1}: Loss {epoch_loss:.4f}, Accuracy {epoch_acc:.4f}")

"""# Step 5: Comparison & Results
This block generates Confusion Matrices and Performance Graphs for all three models.
"""

# ==========================================
# PART 5: COMPARISON & METRICS (FIXED)
# ==========================================
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import torch

# -----------------------------
# Helper Function for Reports
# -----------------------------
def generate_report(y_true, y_pred, title):
    print(f"\n--- {title} Report ---")
    print(classification_report(y_true, y_pred))

    cm = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(5,4))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
    plt.title(f"{title} Confusion Matrix")
    plt.xlabel('Predicted')
    plt.ylabel('Actual')
    plt.show()

# ----------------------------------
# 1. KERAS PREDICTIONS
# ----------------------------------
y_pred_keras = keras_model.predict(test_data_keras, verbose=1)
y_pred_keras = (y_pred_keras > 0.5).astype("int32").flatten()
y_true_keras = test_data_keras.classes

# ----------------------------------
# 2. TENSORFLOW CUSTOM PREDICTIONS
# ----------------------------------
y_pred_tf = tf_model.predict(test_data_keras, verbose=1)
y_pred_tf = (y_pred_tf > 0.5).astype("int32").flatten()
y_true_tf = test_data_keras.classes

# ----------------------------------
# 3. PYTORCH PREDICTIONS
# ----------------------------------
pt_model.eval()
y_pred_pt = []
y_true_pt = []

with torch.no_grad():
    for inputs, labels in test_loader:
        inputs = inputs.to(device)
        labels = labels.unsqueeze(1).to(device)  # Ensure shape [batch,1]
        outputs = pt_model(inputs)
        predicted = (outputs > 0.5).float().cpu().numpy()
        y_pred_pt.extend(predicted)
        y_true_pt.extend(labels.cpu().numpy())

y_pred_pt = np.array(y_pred_pt).flatten().astype(int)
y_true_pt = np.array(y_true_pt).flatten().astype(int)

# ----------------------------------
# 4. GENERATE REPORTS
# ----------------------------------
generate_report(y_true_keras, y_pred_keras, "Keras Functional")
generate_report(y_true_tf, y_pred_tf, "TensorFlow Custom")
generate_report(y_true_pt, y_pred_pt, "PyTorch")

# ----------------------------------
# 5. TRAINING CURVE COMPARISON
# ----------------------------------
plt.figure(figsize=(12, 5))

# Accuracy
plt.subplot(1, 2, 1)
plt.plot(history_keras.history['accuracy'], label='Keras')
plt.plot(history_tf.history['accuracy'], label='TensorFlow Custom')
plt.plot(pt_acc_history, label='PyTorch')
plt.title('Model Accuracy Comparison')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()

# Loss
plt.subplot(1, 2, 2)
plt.plot(history_keras.history['loss'], label='Keras')
plt.plot(history_tf.history['loss'], label='TensorFlow Custom')
plt.plot(pt_loss_history, label='PyTorch')
plt.title('Model Loss Comparison')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()

plt.tight_layout()
plt.show()

"""## Step 6: Comparison & Results for efficient"""

# ==========================================
# PART 6: EFFICIENTNET COMPARISON & METRICS
# ==========================================
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# -----------------------------
# Helper Function (Same)
# -----------------------------
def generate_report(y_true, y_pred, title):
    print(f"\n--- {title} Report ---")
    print(classification_report(y_true, y_pred))

    cm = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(5,4))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Greens')
    plt.title(f"{title} Confusion Matrix")
    plt.xlabel('Predicted')
    plt.ylabel('Actual')
    plt.show()


# ----------------------------------
# 1. EFFICIENTNET PREDICTIONS (TF)
# ----------------------------------
y_pred_eff = tf_efficientnet_model.predict(test_data_keras, verbose=1)
y_pred_eff = (y_pred_eff > 0.5).astype("int32").flatten()
y_true_eff = test_data_keras.classes


# ----------------------------------
# 2. GENERATE REPORT
# ----------------------------------
generate_report(y_true_eff, y_pred_eff, "EfficientNet Model")


# ----------------------------------
# 3. TRAINING CURVE (EFFICIENTNET)
# ----------------------------------
plt.figure(figsize=(12,5))

# Accuracy
plt.subplot(1,2,1)
plt.plot(history_tf_eff.history['accuracy'], label='EfficientNet', color='green')
plt.title('EfficientNet Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()

# Loss
plt.subplot(1,2,2)
plt.plot(history_tf_eff.history['loss'], label='EfficientNet', color='red')
plt.title('EfficientNet Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()

plt.tight_layout()
plt.show()

"""# Step 6: Explainable AI
This block generates Explainable ai results using lime and Shap for all three models.
"""

!pip install lime

"""## lime explainable AI (For Keras)

"""

# from lime import lime_image
# from skimage.segmentation import mark_boundaries
# import numpy as np
# import matplotlib.pyplot as plt

# # Get one sample image
# img, label = test_data_keras[0]
# img = img[0]  # Take first image from batch

# explainer = lime_image.LimeImageExplainer()

# def keras_predict(images):
#     images = np.array(images)
#     return np.concatenate([
#         1 - keras_model.predict(images),
#         keras_model.predict(images)
#     ], axis=1)

# explanation = explainer.explain_instance(
#     img.astype('double'),
#     keras_predict,
#     top_labels=2,
#     hide_color=0,
#     num_samples=1000
# )

# # Show explanation
# temp, mask = explanation.get_image_and_mask(
#     explanation.top_labels[0],
#     positive_only=True,
#     num_features=5,
#     hide_rest=False
# )

# plt.imshow(mark_boundaries(temp / 2 + 0.5, mask))
# plt.title("LIME Explanation (Keras Model)")
# plt.axis('off')
# plt.show()

"""### LIME for TensorFlow Custom Mode"""

# # ==========================================
# # LIME EXPLANATION (NO test_df ERROR)
# # ==========================================

# !pip install lime

# from lime import lime_image
# from skimage.segmentation import mark_boundaries
# import numpy as np
# import matplotlib.pyplot as plt
# from tensorflow.keras.preprocessing import image
# from tensorflow.keras.applications.densenet import preprocess_input

# # ==========================================
# # 1. LOAD IMAGE DIRECTLY FROM FOLDER
# # ==========================================

# img_path = "/content/drive/MyDrive/final_images_C/Normal/your_image.jpg"
# # 👆 Replace with any image path from your dataset

# img = image.load_img(img_path, target_size=(224, 224))
# img = image.img_to_array(img)
# img = preprocess_input(img)

# # ==========================================
# # 2. LIME EXPLAINER
# # ==========================================

# explainer = lime_image.LimeImageExplainer()

# # ==========================================
# # 3. PREDICTION FUNCTION
# # ==========================================

# def tf_predict(images):
#     images = np.array(images)
#     images = preprocess_input(images.copy())
#     preds = tf_model.predict(images)
#     return np.concatenate([1 - preds, preds], axis=1)

# # ==========================================
# # 4. GENERATE EXPLANATION
# # ==========================================

# explanation = explainer.explain_instance(
#     img.astype('double'),
#     tf_predict,
#     top_labels=2,
#     hide_color=0,
#     num_samples=1000
# )

# # ==========================================
# # 5. VISUALIZE
# # ==========================================

# temp, mask = explanation.get_image_and_mask(
#     explanation.top_labels[0],
#     positive_only=True,
#     num_features=5,
#     hide_rest=False
# )

# plt.imshow(mark_boundaries(temp / 2 + 0.5, mask))
# plt.title("LIME Explanation (TF Custom Model)")
# plt.axis('off')
# plt.show()

"""## SHAP"""

!pip install shap

import shap
import numpy as np
import tensorflow as tf
from tensorflow.keras.applications.resnet50 import preprocess_input

# -------------------------------
# 1. Prepare background dataset
# -------------------------------
background = test_data_keras[0][0][:50].copy()
background = preprocess_input(background)

# -------------------------------
# 2. Select test images
# -------------------------------
test_images = test_data_keras[1][0][:5].copy()
test_images = preprocess_input(test_images)

# -------------------------------
# 3. Use GradientExplainer (IMPORTANT)
# -------------------------------
explainer = shap.GradientExplainer(keras_model, background)

# -------------------------------
# 4. Get SHAP values
# -------------------------------
shap_values = explainer.shap_values(test_images)

# -------------------------------
# 5. Select correct class (binary case)
# -------------------------------
# If output shape = (None, 1)
shap_values = shap_values[0]

# -------------------------------
# 6. Plot with better visibility
# -------------------------------
shap.image_plot(
    shap_values,
    test_images,
    show=True
)

explainer = shap.DeepExplainer(tf_model, background)

import shap

# Convert model to evaluation mode
pt_model.eval()

# Select background
background, _ = next(iter(test_loader))
background = background[:50].to(device)

# Create SHAP explainer
explainer = shap.DeepExplainer(pt_model, background)

# Test images
test_images, _ = next(iter(test_loader))
test_images = test_images[:5].to(device)

# Compute SHAP values
shap_values = explainer.shap_values(test_images)

# Move to CPU for plotting
test_images = test_images.cpu().numpy()
shap_values = [sv.cpu().numpy() for sv in shap_values]

# Plot
shap.image_plot(shap_values, test_images)